version: '3.3'
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    hostname: dynamodb
    ports:
      - "8000:8000"
    volumes:
      - ~/dynamodb/data:/home/dynamodb/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodb/data/"

